Home 2
GroofiP/Geek_PyQt pull request #2
Opened 2021-07-13 01:31 UTC by GroofiP

2021-07-20 17:47 UTC, Ma007ks requested changes
Заочно ставлю удовлетворительно, но задание нужно доделать.
Я добавил незаконченные примеры решений для дескриптора и метаклассов, их нужно взять за основу.

2021-07-20 17:47 UTC, Ma007ks commented on Client_Server/server_cls.py
> +            elif key == "server_con":
У сервера может и не быть атрибута `server_con`

2021-07-20 17:47 UTC, Ma007ks commented on Client_Server/server_cls.py
> +        self.tcp = PortVerifier(tcp).tcp
Дескрипторы нужно определять на уровне класса

2021-07-20 17:47 UTC, Ma007ks commented on Client_Server/server_cls.py
> +class PortVerifier:
Этот класс не является дескриптором, у него нет ни одного метода из `__get__`, `__set__` и `__del__`

2021-07-22 15:02 UTC, GroofiP commented on Client_Server/server_cls.py
> +            elif key == "server_con":
Сделаны , все замечание в 4 дз! Спасибо!

2021-07-22 15:02 UTC, closed without merging